# Generated by Django 2.2 on 2020-10-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20201007_0152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Publications'},
        ),
    ]
