# Generated by Django 2.2 on 2020-10-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20201007_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('Section_1', models.TextField()),
                ('Section_2', models.TextField()),
                ('Section_3', models.TextField()),
                ('Section_4', models.TextField()),
                ('Section_5', models.TextField()),
            ],
        ),
    ]
